export const countries = [
  {
    code: "FR",
    name: "France",
    emoji: "🇫🇷",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "BE",
    name: "Belgium",
    emoji: "🇧🇪",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "DE",
    name: "Germany",
    emoji: "🇩🇪",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "IT",
    name: "Italy",
    emoji: "🇮🇹",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "ES",
    name: "Spain",
    emoji: "🇪🇸",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "PT",
    name: "Portugal",
    emoji: "🇵🇹",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "NL",
    name: "Netherlands",
    emoji: "🇳🇱",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "PL",
    name: "Poland",
    emoji: "🇵🇱",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "GR",
    name: "Greece",
    emoji: "🇬🇷",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "CH",
    name: "Switzerland",
    emoji: "🇨🇭",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "SE",
    name: "Sweden",
    emoji: "🇸🇪",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "NO",
    name: "Norway",
    emoji: "🇳🇴",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "FI",
    name: "Finland",
    emoji: "🇫🇮",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "DK",
    name: "Denmark",
    emoji: "🇩🇰",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "IE",
    name: "Ireland",
    emoji: "🇮🇪",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "UK",
    name: "United Kingdom",
    emoji: "🇬🇧",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "RU",
    name: "Russia",
    emoji: "🇷🇺",
    continentName: "Europe",
    continentCode: "EU",
  },
  {
    code: "US",
    name: "United States",
    emoji: "🇺🇸",
    continentName: "North America",
    continentCode: "NA",
  },
  {
    code: "CA",
    name: "Canada",
    emoji: "🇨🇦",
    continentName: "North America",
    continentCode: "NA",
  },
  {
    code: "MX",
    name: "Mexico",
    emoji: "🇲🇽",
    continentName: "North America",
    continentCode: "NA",
  },
  {
    code: "BR",
    name: "Brazil",
    emoji: "🇧🇷",
    continentName: "South America",
    continentCode: "SA",
  },
  {
    code: "AR",
    name: "Argentina",
    emoji: "🇦🇷",
    continentName: "South America",
    continentCode: "SA",
  },
  {
    code: "CL",
    name: "Chile",
    emoji: "🇨🇱",
    continentName: "South America",
    continentCode: "SA",
  },
  {
    code: "CO",
    name: "Colombia",
    emoji: "🇨🇴",
    continentName: "South America",
    continentCode: "SA",
  },
  {
    code: "PE",
    name: "Peru",
    emoji: "🇵🇪",
    continentName: "South America",
    continentCode: "SA",
  },
  {
    code: "AU",
    name: "Australia",
    emoji: "🇦🇺",
    continentName: "Oceania",
    continentCode: "OC",
  },
  {
    code: "NZ",
    name: "New Zealand",
    emoji: "🇳🇿",
    continentName: "Oceania",
    continentCode: "OC",
  },
  {
    code: "CN",
    name: "China",
    emoji: "🇨🇳",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "JP",
    name: "Japan",
    emoji: "🇯🇵",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "KR",
    name: "South Korea",
    emoji: "🇰🇷",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "IN",
    name: "India",
    emoji: "🇮🇳",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "ID",
    name: "Indonesia",
    emoji: "🇮🇩",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "TH",
    name: "Thailand",
    emoji: "🇹🇭",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "SG",
    name: "Singapore",
    emoji: "🇸🇬",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "MY",
    name: "Malaysia",
    emoji: "🇲🇾",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "PH",
    name: "Philippines",
    emoji: "🇵🇭",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "ZA",
    name: "South Africa",
    emoji: "🇿🇦",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "EG",
    name: "Egypt",
    emoji: "🇪🇬",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "NG",
    name: "Nigeria",
    emoji: "🇳🇬",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "KE",
    name: "Kenya",
    emoji: "🇰🇪",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "MA",
    name: "Morocco",
    emoji: "🇲🇦",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "DZ",
    name: "Algeria",
    emoji: "🇩🇿",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "TN",
    name: "Tunisia",
    emoji: "🇹🇳",
    continentName: "Africa",
    continentCode: "AF",
  },
  {
    code: "IL",
    name: "Israel",
    emoji: "🇮🇱",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    emoji: "🇸🇦",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    emoji: "🇦🇪",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "TR",
    name: "Turkey",
    emoji: "🇹🇷",
    continentName: "Asia",
    continentCode: "AS",
  },
  {
    code: "IR",
    name: "Iran",
    emoji: "🇮🇷",
    continentName: "Asia",
    continentCode: "AS",
  },
];
